onestock:
  url: https://api.onestock-retail.com/v2/search_orders
  #chat: https://chat.googleapis.com/v1/spaces/AAAAvzlKXkg/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=XJuf1TBA9_Qvqhuc4d9Q-5vx8ZckOL4ZZAb7eLXvCss%3D
  chat: https://chat.googleapis.com/v1/spaces/AAAA_lM8SDk/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=py4MZRqwWoMEg90vXT5Pb59HAe51LfB-L6LTeVqmZhM%3D
  limit: 50
  delta: 60
  batch: 300

firestore:
  project: flows-onestock-prod
  collection: onestock

bigquery:
  project: flows-onestock-prod
  dataset: ingestion
  table_dj: orders_dj
  table_cl: orders_cl